// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in enttest/ent/runtime.go

const (
	Version = "v0.10.2-0.20220625115926-49fc14f12fb2"           // Version of ent codegen.
	Sum     = "h1:YEGJGezKg5W2xKpnDYvxIphxM6Syx/ko5J8gV/6rFhE=" // Sum of ent codegen.
)
