// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"enttest/ent/hashtag"
	"enttest/ent/hashtagtopost"
	"enttest/ent/post"
	"enttest/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HashtagQuery is the builder for querying Hashtag entities.
type HashtagQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Hashtag
	// eager-loading edges.
	withPost          *PostQuery
	withHashtagToPost *HashtagToPostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HashtagQuery builder.
func (hq *HashtagQuery) Where(ps ...predicate.Hashtag) *HashtagQuery {
	hq.predicates = append(hq.predicates, ps...)
	return hq
}

// Limit adds a limit step to the query.
func (hq *HashtagQuery) Limit(limit int) *HashtagQuery {
	hq.limit = &limit
	return hq
}

// Offset adds an offset step to the query.
func (hq *HashtagQuery) Offset(offset int) *HashtagQuery {
	hq.offset = &offset
	return hq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hq *HashtagQuery) Unique(unique bool) *HashtagQuery {
	hq.unique = &unique
	return hq
}

// Order adds an order step to the query.
func (hq *HashtagQuery) Order(o ...OrderFunc) *HashtagQuery {
	hq.order = append(hq.order, o...)
	return hq
}

// QueryPost chains the current query on the "post" edge.
func (hq *HashtagQuery) QueryPost() *PostQuery {
	query := &PostQuery{config: hq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hashtag.Table, hashtag.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, hashtag.PostTable, hashtag.PostPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHashtagToPost chains the current query on the "hashtag_to_post" edge.
func (hq *HashtagQuery) QueryHashtagToPost() *HashtagToPostQuery {
	query := &HashtagToPostQuery{config: hq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hashtag.Table, hashtag.FieldID, selector),
			sqlgraph.To(hashtagtopost.Table, hashtagtopost.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, hashtag.HashtagToPostTable, hashtag.HashtagToPostColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Hashtag entity from the query.
// Returns a *NotFoundError when no Hashtag was found.
func (hq *HashtagQuery) First(ctx context.Context) (*Hashtag, error) {
	nodes, err := hq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hashtag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hq *HashtagQuery) FirstX(ctx context.Context) *Hashtag {
	node, err := hq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Hashtag ID from the query.
// Returns a *NotFoundError when no Hashtag ID was found.
func (hq *HashtagQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = hq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hashtag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hq *HashtagQuery) FirstIDX(ctx context.Context) string {
	id, err := hq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Hashtag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Hashtag entity is found.
// Returns a *NotFoundError when no Hashtag entities are found.
func (hq *HashtagQuery) Only(ctx context.Context) (*Hashtag, error) {
	nodes, err := hq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hashtag.Label}
	default:
		return nil, &NotSingularError{hashtag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hq *HashtagQuery) OnlyX(ctx context.Context) *Hashtag {
	node, err := hq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Hashtag ID in the query.
// Returns a *NotSingularError when more than one Hashtag ID is found.
// Returns a *NotFoundError when no entities are found.
func (hq *HashtagQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = hq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hashtag.Label}
	default:
		err = &NotSingularError{hashtag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hq *HashtagQuery) OnlyIDX(ctx context.Context) string {
	id, err := hq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Hashtags.
func (hq *HashtagQuery) All(ctx context.Context) ([]*Hashtag, error) {
	if err := hq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return hq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (hq *HashtagQuery) AllX(ctx context.Context) []*Hashtag {
	nodes, err := hq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Hashtag IDs.
func (hq *HashtagQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := hq.Select(hashtag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hq *HashtagQuery) IDsX(ctx context.Context) []string {
	ids, err := hq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hq *HashtagQuery) Count(ctx context.Context) (int, error) {
	if err := hq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return hq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (hq *HashtagQuery) CountX(ctx context.Context) int {
	count, err := hq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hq *HashtagQuery) Exist(ctx context.Context) (bool, error) {
	if err := hq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return hq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (hq *HashtagQuery) ExistX(ctx context.Context) bool {
	exist, err := hq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HashtagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hq *HashtagQuery) Clone() *HashtagQuery {
	if hq == nil {
		return nil
	}
	return &HashtagQuery{
		config:            hq.config,
		limit:             hq.limit,
		offset:            hq.offset,
		order:             append([]OrderFunc{}, hq.order...),
		predicates:        append([]predicate.Hashtag{}, hq.predicates...),
		withPost:          hq.withPost.Clone(),
		withHashtagToPost: hq.withHashtagToPost.Clone(),
		// clone intermediate query.
		sql:    hq.sql.Clone(),
		path:   hq.path,
		unique: hq.unique,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HashtagQuery) WithPost(opts ...func(*PostQuery)) *HashtagQuery {
	query := &PostQuery{config: hq.config}
	for _, opt := range opts {
		opt(query)
	}
	hq.withPost = query
	return hq
}

// WithHashtagToPost tells the query-builder to eager-load the nodes that are connected to
// the "hashtag_to_post" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HashtagQuery) WithHashtagToPost(opts ...func(*HashtagToPostQuery)) *HashtagQuery {
	query := &HashtagToPostQuery{config: hq.config}
	for _, opt := range opts {
		opt(query)
	}
	hq.withHashtagToPost = query
	return hq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (hq *HashtagQuery) GroupBy(field string, fields ...string) *HashtagGroupBy {
	grbuild := &HashtagGroupBy{config: hq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return hq.sqlQuery(ctx), nil
	}
	grbuild.label = hashtag.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (hq *HashtagQuery) Select(fields ...string) *HashtagSelect {
	hq.fields = append(hq.fields, fields...)
	selbuild := &HashtagSelect{HashtagQuery: hq}
	selbuild.label = hashtag.Label
	selbuild.flds, selbuild.scan = &hq.fields, selbuild.Scan
	return selbuild
}

func (hq *HashtagQuery) prepareQuery(ctx context.Context) error {
	for _, f := range hq.fields {
		if !hashtag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hq.path != nil {
		prev, err := hq.path(ctx)
		if err != nil {
			return err
		}
		hq.sql = prev
	}
	return nil
}

func (hq *HashtagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Hashtag, error) {
	var (
		nodes       = []*Hashtag{}
		_spec       = hq.querySpec()
		loadedTypes = [2]bool{
			hq.withPost != nil,
			hq.withHashtagToPost != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*Hashtag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &Hashtag{config: hq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := hq.withPost; query != nil {
		edgeids := make([]driver.Value, len(nodes))
		byid := make(map[string]*Hashtag)
		nids := make(map[string]map[*Hashtag]struct{})
		for i, node := range nodes {
			edgeids[i] = node.ID
			byid[node.ID] = node
			node.Edges.Post = []*Post{}
		}
		query.Where(func(s *sql.Selector) {
			joinT := sql.Table(hashtag.PostTable)
			s.Join(joinT).On(s.C(post.FieldID), joinT.C(hashtag.PostPrimaryKey[0]))
			s.Where(sql.InValues(joinT.C(hashtag.PostPrimaryKey[1]), edgeids...))
			columns := s.SelectedColumns()
			s.Select(joinT.C(hashtag.PostPrimaryKey[1]))
			s.AppendSelect(columns...)
			s.SetDistinct(false)
		})
		neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]interface{}, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]interface{}{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []interface{}) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*Hashtag]struct{}{byid[outValue]: struct{}{}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byid[outValue]] = struct{}{}
				return nil
			}
		})
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "post" node returned %v`, n.ID)
			}
			for kn := range nodes {
				kn.Edges.Post = append(kn.Edges.Post, n)
			}
		}
	}

	if query := hq.withHashtagToPost; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[string]*Hashtag)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.HashtagToPost = []*HashtagToPost{}
		}
		query.Where(predicate.HashtagToPost(func(s *sql.Selector) {
			s.Where(sql.InValues(hashtag.HashtagToPostColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.HashtagID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "hashtag_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.HashtagToPost = append(node.Edges.HashtagToPost, n)
		}
	}

	return nodes, nil
}

func (hq *HashtagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hq.querySpec()
	_spec.Node.Columns = hq.fields
	if len(hq.fields) > 0 {
		_spec.Unique = hq.unique != nil && *hq.unique
	}
	return sqlgraph.CountNodes(ctx, hq.driver, _spec)
}

func (hq *HashtagQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := hq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (hq *HashtagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   hashtag.Table,
			Columns: hashtag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: hashtag.FieldID,
			},
		},
		From:   hq.sql,
		Unique: true,
	}
	if unique := hq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := hq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hashtag.FieldID)
		for i := range fields {
			if fields[i] != hashtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hq *HashtagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hq.driver.Dialect())
	t1 := builder.Table(hashtag.Table)
	columns := hq.fields
	if len(columns) == 0 {
		columns = hashtag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hq.sql != nil {
		selector = hq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hq.unique != nil && *hq.unique {
		selector.Distinct()
	}
	for _, p := range hq.predicates {
		p(selector)
	}
	for _, p := range hq.order {
		p(selector)
	}
	if offset := hq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HashtagGroupBy is the group-by builder for Hashtag entities.
type HashtagGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hgb *HashtagGroupBy) Aggregate(fns ...AggregateFunc) *HashtagGroupBy {
	hgb.fns = append(hgb.fns, fns...)
	return hgb
}

// Scan applies the group-by query and scans the result into the given value.
func (hgb *HashtagGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := hgb.path(ctx)
	if err != nil {
		return err
	}
	hgb.sql = query
	return hgb.sqlScan(ctx, v)
}

func (hgb *HashtagGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range hgb.fields {
		if !hashtag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := hgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (hgb *HashtagGroupBy) sqlQuery() *sql.Selector {
	selector := hgb.sql.Select()
	aggregation := make([]string, 0, len(hgb.fns))
	for _, fn := range hgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(hgb.fields)+len(hgb.fns))
		for _, f := range hgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(hgb.fields...)...)
}

// HashtagSelect is the builder for selecting fields of Hashtag entities.
type HashtagSelect struct {
	*HashtagQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (hs *HashtagSelect) Scan(ctx context.Context, v interface{}) error {
	if err := hs.prepareQuery(ctx); err != nil {
		return err
	}
	hs.sql = hs.HashtagQuery.sqlQuery(ctx)
	return hs.sqlScan(ctx, v)
}

func (hs *HashtagSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := hs.sql.Query()
	if err := hs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
