// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"enttest/ent/hashtag"
	"enttest/ent/hashtagtopost"
	"enttest/ent/post"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HashtagCreate is the builder for creating a Hashtag entity.
type HashtagCreate struct {
	config
	mutation *HashtagMutation
	hooks    []Hook
}

// SetID sets the "id" field.
func (hc *HashtagCreate) SetID(s string) *HashtagCreate {
	hc.mutation.SetID(s)
	return hc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (hc *HashtagCreate) SetNillableID(s *string) *HashtagCreate {
	if s != nil {
		hc.SetID(*s)
	}
	return hc
}

// AddPostIDs adds the "post" edge to the Post entity by IDs.
func (hc *HashtagCreate) AddPostIDs(ids ...string) *HashtagCreate {
	hc.mutation.AddPostIDs(ids...)
	return hc
}

// AddPost adds the "post" edges to the Post entity.
func (hc *HashtagCreate) AddPost(p ...*Post) *HashtagCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return hc.AddPostIDs(ids...)
}

// AddHashtagToPostIDs adds the "hashtag_to_post" edge to the HashtagToPost entity by IDs.
func (hc *HashtagCreate) AddHashtagToPostIDs(ids ...string) *HashtagCreate {
	hc.mutation.AddHashtagToPostIDs(ids...)
	return hc
}

// AddHashtagToPost adds the "hashtag_to_post" edges to the HashtagToPost entity.
func (hc *HashtagCreate) AddHashtagToPost(h ...*HashtagToPost) *HashtagCreate {
	ids := make([]string, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hc.AddHashtagToPostIDs(ids...)
}

// Mutation returns the HashtagMutation object of the builder.
func (hc *HashtagCreate) Mutation() *HashtagMutation {
	return hc.mutation
}

// Save creates the Hashtag in the database.
func (hc *HashtagCreate) Save(ctx context.Context) (*Hashtag, error) {
	var (
		err  error
		node *Hashtag
	)
	hc.defaults()
	if len(hc.hooks) == 0 {
		if err = hc.check(); err != nil {
			return nil, err
		}
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HashtagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hc.check(); err != nil {
				return nil, err
			}
			hc.mutation = mutation
			if node, err = hc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			if hc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, hc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Hashtag)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from HashtagMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HashtagCreate) SaveX(ctx context.Context) *Hashtag {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HashtagCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HashtagCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HashtagCreate) defaults() {
	if _, ok := hc.mutation.ID(); !ok {
		v := hashtag.DefaultID()
		hc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HashtagCreate) check() error {
	if v, ok := hc.mutation.ID(); ok {
		if err := hashtag.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Hashtag.id": %w`, err)}
		}
	}
	return nil
}

func (hc *HashtagCreate) sqlSave(ctx context.Context) (*Hashtag, error) {
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Hashtag.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (hc *HashtagCreate) createSpec() (*Hashtag, *sqlgraph.CreateSpec) {
	var (
		_node = &Hashtag{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: hashtag.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: hashtag.FieldID,
			},
		}
	)
	if id, ok := hc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := hc.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   hashtag.PostTable,
			Columns: hashtag.PostPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &HashtagToPostCreate{config: hc.config, mutation: newHashtagToPostMutation(hc.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hc.mutation.HashtagToPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hashtag.HashtagToPostTable,
			Columns: []string{hashtag.HashtagToPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: hashtagtopost.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HashtagCreateBulk is the builder for creating many Hashtag entities in bulk.
type HashtagCreateBulk struct {
	config
	builders []*HashtagCreate
}

// Save creates the Hashtag entities in the database.
func (hcb *HashtagCreateBulk) Save(ctx context.Context) ([]*Hashtag, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hashtag, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HashtagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HashtagCreateBulk) SaveX(ctx context.Context) []*Hashtag {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HashtagCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HashtagCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
