// Code generated by ent, DO NOT EDIT.

package ent

import (
	"enttest/ent/post"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges PostEdges `json:"edges"`
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// Hashtags holds the value of the hashtags edge.
	Hashtags []*Hashtag `json:"hashtags,omitempty"`
	// HashtagToPost holds the value of the hashtag_to_post edge.
	HashtagToPost []*HashtagToPost `json:"hashtag_to_post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// HashtagsOrErr returns the Hashtags value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) HashtagsOrErr() ([]*Hashtag, error) {
	if e.loadedTypes[0] {
		return e.Hashtags, nil
	}
	return nil, &NotLoadedError{edge: "hashtags"}
}

// HashtagToPostOrErr returns the HashtagToPost value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) HashtagToPostOrErr() ([]*HashtagToPost, error) {
	if e.loadedTypes[1] {
		return e.HashtagToPost, nil
	}
	return nil, &NotLoadedError{edge: "hashtag_to_post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Post) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case post.FieldID, post.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Post", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Post fields.
func (po *Post) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case post.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				po.ID = value.String
			}
		case post.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				po.Title = value.String
			}
		}
	}
	return nil
}

// QueryHashtags queries the "hashtags" edge of the Post entity.
func (po *Post) QueryHashtags() *HashtagQuery {
	return (&PostClient{config: po.config}).QueryHashtags(po)
}

// QueryHashtagToPost queries the "hashtag_to_post" edge of the Post entity.
func (po *Post) QueryHashtagToPost() *HashtagToPostQuery {
	return (&PostClient{config: po.config}).QueryHashtagToPost(po)
}

// Update returns a builder for updating this Post.
// Note that you need to call Post.Unwrap() before calling this method if this Post
// was returned from a transaction, and the transaction was committed or rolled back.
func (po *Post) Update() *PostUpdateOne {
	return (&PostClient{config: po.config}).UpdateOne(po)
}

// Unwrap unwraps the Post entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (po *Post) Unwrap() *Post {
	_tx, ok := po.config.driver.(*txDriver)
	if !ok {
		panic("ent: Post is not a transactional entity")
	}
	po.config.driver = _tx.drv
	return po
}

// String implements the fmt.Stringer.
func (po *Post) String() string {
	var builder strings.Builder
	builder.WriteString("Post(")
	builder.WriteString(fmt.Sprintf("id=%v, ", po.ID))
	builder.WriteString("title=")
	builder.WriteString(po.Title)
	builder.WriteByte(')')
	return builder.String()
}

// Posts is a parsable slice of Post.
type Posts []*Post

func (po Posts) config(cfg config) {
	for _i := range po {
		po[_i].config = cfg
	}
}
