// Code generated by ent, DO NOT EDIT.

package hashtagtopost

import (
	"enttest/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// HashtagID applies equality check predicate on the "hashtag_id" field. It's identical to HashtagIDEQ.
func HashtagID(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHashtagID), v))
	})
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPostID), v))
	})
}

// HashtagIDEQ applies the EQ predicate on the "hashtag_id" field.
func HashtagIDEQ(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHashtagID), v))
	})
}

// HashtagIDNEQ applies the NEQ predicate on the "hashtag_id" field.
func HashtagIDNEQ(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHashtagID), v))
	})
}

// HashtagIDIn applies the In predicate on the "hashtag_id" field.
func HashtagIDIn(vs ...string) predicate.HashtagToPost {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.HashtagToPost(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldHashtagID), v...))
	})
}

// HashtagIDNotIn applies the NotIn predicate on the "hashtag_id" field.
func HashtagIDNotIn(vs ...string) predicate.HashtagToPost {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.HashtagToPost(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldHashtagID), v...))
	})
}

// HashtagIDGT applies the GT predicate on the "hashtag_id" field.
func HashtagIDGT(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHashtagID), v))
	})
}

// HashtagIDGTE applies the GTE predicate on the "hashtag_id" field.
func HashtagIDGTE(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHashtagID), v))
	})
}

// HashtagIDLT applies the LT predicate on the "hashtag_id" field.
func HashtagIDLT(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHashtagID), v))
	})
}

// HashtagIDLTE applies the LTE predicate on the "hashtag_id" field.
func HashtagIDLTE(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHashtagID), v))
	})
}

// HashtagIDContains applies the Contains predicate on the "hashtag_id" field.
func HashtagIDContains(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldHashtagID), v))
	})
}

// HashtagIDHasPrefix applies the HasPrefix predicate on the "hashtag_id" field.
func HashtagIDHasPrefix(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldHashtagID), v))
	})
}

// HashtagIDHasSuffix applies the HasSuffix predicate on the "hashtag_id" field.
func HashtagIDHasSuffix(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldHashtagID), v))
	})
}

// HashtagIDEqualFold applies the EqualFold predicate on the "hashtag_id" field.
func HashtagIDEqualFold(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldHashtagID), v))
	})
}

// HashtagIDContainsFold applies the ContainsFold predicate on the "hashtag_id" field.
func HashtagIDContainsFold(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldHashtagID), v))
	})
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPostID), v))
	})
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPostID), v))
	})
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...string) predicate.HashtagToPost {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.HashtagToPost(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPostID), v...))
	})
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...string) predicate.HashtagToPost {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.HashtagToPost(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPostID), v...))
	})
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPostID), v))
	})
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPostID), v))
	})
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPostID), v))
	})
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPostID), v))
	})
}

// PostIDContains applies the Contains predicate on the "post_id" field.
func PostIDContains(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPostID), v))
	})
}

// PostIDHasPrefix applies the HasPrefix predicate on the "post_id" field.
func PostIDHasPrefix(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPostID), v))
	})
}

// PostIDHasSuffix applies the HasSuffix predicate on the "post_id" field.
func PostIDHasSuffix(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPostID), v))
	})
}

// PostIDEqualFold applies the EqualFold predicate on the "post_id" field.
func PostIDEqualFold(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPostID), v))
	})
}

// PostIDContainsFold applies the ContainsFold predicate on the "post_id" field.
func PostIDContainsFold(v string) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPostID), v))
	})
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PostTable, PostFieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PostInverseTable, PostFieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PostTable, PostColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHashtag applies the HasEdge predicate on the "hashtag" edge.
func HasHashtag() predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(HashtagTable, HashtagFieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HashtagTable, HashtagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHashtagWith applies the HasEdge predicate on the "hashtag" edge with a given conditions (other predicates).
func HasHashtagWith(preds ...predicate.Hashtag) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(HashtagInverseTable, HashtagFieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HashtagTable, HashtagColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HashtagToPost) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HashtagToPost) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HashtagToPost) predicate.HashtagToPost {
	return predicate.HashtagToPost(func(s *sql.Selector) {
		p(s.Not())
	})
}
